INSERT INTO [dbo].[Sales] ([TransactionId]
,[CustomerId]
,[ProductId]
,[Quantity]
,[Price]
,[TotalAmount]
,[TransactionDate]
,[ProfitAmount]
,[Hour]
,[Minute]
,[StoreId]) ( Select [TransactionId]
,[CustomerId]
,[ProductId]
,[Quantity]
,[Price]
,[TotalAmount]
,[TransactionDate]
,[ProfitAmount]
,[Hour]
,[Minute]
,[StoreId] FROM Sales)