import { ReactFlow, Position, Handle } from "@xyflow/react";

export const AllNodes = [
  {
    id: "nl1-1",
    sourcePosition: Position.Right,
    position: { x: 20, y: 0 },
    isParent: true,
    type: "custom",

    data: {
      id: "nl1-1",
      isSource: true,
      isSolutionPlay: true,
      label: "Cloud & AI Platform",
      nodes: ["nl2-1", "nl2-2", "nl2-3", "nl2-4"],

      isDisabled: false,
      isActive: true,
      visibility: "visible",
    },
  },
  {
    id: "nl1-2",
    sourcePosition: Position.Right,
    position: { x: 20, y: 80 },
    isParent: true,
    type: "custom",
    data: {
      id: "nl1-2",

      isSolutionPlay: true,
      isSource: true,
      label: "AI Business Solution",
      nodes: [],
      isDisabled: true,
      visibility: "visible",
    },
  },
  {
    id: "nl1-3",
    sourcePosition: Position.Right,
    position: { x: 20, y: 160 },
    isParent: true,

    type: "custom",
    data: {
      id: "nl1-3",
      isSolutionPlay: true,
      isSource: true,
      label: "Security",
      nodes: [],
      isDisabled: true,
      visibility: "visible",
    },
  },

  {
    id: "nl2-1",
    position: { x: 350, y: 0 },
    type: "custom",

    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    data: {
      id: "nl2-1",
      label:
        "Demo 1a: Innovate with Azure AI Apps and Agents - Customer and Store planner",
      isDisabled: true,
      nodes: ["nl3-18", "nl3-17"],
      display: "none",
      visibility: "hidden",
    },
  },
  {
    id: "nl2-2",

    position: { x: 350, y: 80 },
    type: "custom",
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
    data: {
      id: "nl2-2",
      label:
        "Demo 1b: Innovate with Azure AI Apps and Agents - Developer Journey",
      isDisabled: true,
      nodes: [],
      visibility: "hidden",
      display: "none",
    },
  },
  {
    id: "nl2-3",

    position: { x: 350, y: 160 },
    type: "custom",
    targetPosition: Position.Left,

    data: {
      id: "nl2-3",
      label: "Demo 2: Unify Your Data Platform",
      isDisabled: true,
      nodes: ["nl3-10", "nl3-14", "nl3-16"],
      visibility: "hidden",
      display: "none",
    },
  },
  {
    id: "nl2-4",

    position: { x: 350, y: 240 },
    type: "custom",
    targetPosition: Position.Left,

    data: {
      id: "nl2-4",
      label: "Demo 3: Migrate and Modernize Your Estate",
      nodes: [],
      display: "none",
      isDisabled: true,
      visibility: "hidden",
    },
  },

  {
    id: "nl3-14",
    position: { x: 680, y: 0 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-14",
      label: "Level 1: BDM View - Executive/Account Lead POV",
      level: 3,
      isDisabled: true,
      visibility: "hidden",
      display: "none",
      nodes: ["nl4-6", "nl4-7", "nl4-8", "nl4-9", "nl4-10"],
    },
  },

  {
    id: "nl3-10",
    position: { x: 680, y: 80 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,
    data: {
      id: "nl3-10",
      label: "Level 2: TDM View -  Architect/Technical Specialist POV",
      level: 3,
      isDisabled: true,
      visibility: "hidden",
      display: "none",
      nodes: ["nl4-1", "nl4-2", "nl4-3", "nl4-4", "nl4-5"],
    },
  },

  {
    id: "nl3-16",
    position: { x: 680, y: 160 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,
    data: {
      id: "nl3-16",
      label:
        "Level 3: TDM View - Product differentiators/deep dive for solution Engineers",
      level: 3,
      isDisabled: true,
      display: "none",
      visibility: "hidden",
    },
  },
  {
    id: "nl3-17",
    position: { x: 680, y: 0 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-17",
      label: "Level 1: BDM Version ",
      level: 3,
      isDisabled: true,
      display: "none",
      visibility: "hidden",
      nodes: ["nl4-6", "nl4-7"],
    },
  },
  {
    id: "nl3-18",
    position: { x: 680, y: 80 },
    type: "custom",
    targetPosition: Position.Left,
    level: 3,

    data: {
      id: "nl3-18",
      label: "Level 2: TDM Version ",
      level: 3,
      isDisabled: true,
      display: "none",
      visibility: "hidden",
      nodes: [],
    },
  },
  {
    id: "nl4-1",
    position: { x: 1010, y: 0 },
    type: "custom",
    targetPosition: Position.Left,
    level: 4,
    data: {
      id: "nl4-1",
      label: "Chapter 1: Ingest + unify a Disconnected Estate",
      level: 4,
      isDisabled: true,
      visibility: "hidden",
      display: "none",
    },
  },
  {
    id: "nl4-2",
    position: { x: 1010, y: 80 },
    type: "custom",
    targetPosition: Position.Left,
    level: 4,
    data: {
      id: "nl4-2",
      label: "Chapter 2: AI Agents + Insights from OneLake ",
      level: 4,
      isDisabled: true,
      visibility: "hidden",
      display: "none",
    },
  },
  {
    id: "nl4-3",
    position: { x: 1010, y: 160 },
    type: "custom",
    targetPosition: Position.Left,
    level: 4,
    data: {
      id: "nl4-3",
      label: "Chapter 3: Data Science + AI Workflows",
      level: 4,
      isDisabled: true,
      visibility: "hidden",
      display: "none",
      url: "#/copilot-for-data-science-in-fabric",
    },
  },
  {
    id: "nl4-4",
    position: { x: 1010, y: 240 },
    type: "custom",
    targetPosition: Position.Left,
    level: 4,
    data: {
      id: "nl4-4",
      label: "Chapter 4: Power BI + Copilot for Business Analysts",
      level: 4,
      isDisabled: true,
      url: "#/powerbi-experience",
      visibility: "hidden",
      display: "none",
    },
  },
  {
    id: "nl4-5",
    position: { x: 1010, y: 320 },
    type: "custom",
    targetPosition: Position.Left,
    level: 4,
    data: {
      id: "nl4-5",
      label: "Chapter 5: Security, Governance, and Scaling",
      level: 4,
      isDisabled: true,
      url: "",
      display: "none",
      visibility: "hidden",
    },
  },
  {
    id: "nl4-6",
    position: { x: 1010, y: 0 },
    type: "custom",
    targetPosition: Position.Left,
    level: 4,
    data: {
      id: "nl4-6",
      label: "Chapter 1: The Improved Customer Experience",
      level: 4,
      isDisabled: true,
      visibility: "hidden",
      display: "none",
      url: "#/elevated-customer-experience",
    },
  },
  {
    id: "nl4-7",
    position: { x: 1010, y: 80 },
    type: "custom",
    targetPosition: Position.Left,
    level: 4,
    data: {
      id: "nl4-7",
      label: "Chapter 2: Smarter Inventory for Store Managers ",
      level: 4,
      isDisabled: true,
      visibility: "hidden",
      display: "none",
    },
  },
  // {
  //   id: "nl4-8",
  //   position: { x: 1010, y: 140 },
  //   type: "custom",
  //   targetPosition: Position.Left,
  //   level: 4,
  //   data: {
  //     id: "nl4-8",
  //     label: "Chapter 3",
  //     level: 4,
  //     isDisabled: true,
  //     visibility: "hidden",
  //     display: "none",

  //     url: "",
  //   },
  // },
  // {
  //   id: "nl4-9",
  //   position: { x: 1010, y: 210 },
  //   type: "custom",
  //   targetPosition: Position.Left,
  //   level: 4,
  //   data: {
  //     id: "nl4-9",
  //     label: "Chapter 4",
  //     level: 4,
  //     isDisabled: true,
  //     url: "",
  //     visibility: "hidden",
  //     display: "none",
  //   },
  // },
  // {
  //   id: "nl4-10",
  //   position: { x: 1010, y: 280 },
  //   type: "custom",
  //   targetPosition: Position.Left,
  //   level: 4,
  //   data: {
  //     id: "nl4-10",
  //     label: "Chapter 5",
  //     level: 4,
  //     isDisabled: true,
  //     url: "",
  //     visibility: "hidden",
  //     display: "none",
  //   },
  // },
];
