
create table [dbo].dim_products (ProductName NVARCHAR(500), Description NVARCHAR(500), Price FLOAT, Category NVARCHAR(100), StockQuantity INT)



INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ScreenGuard Pro', 'Tempered glass screen protector', 7.28,'Accessory',79);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('CaseMate X', 'Durable phone case', 6.19,'Accessory',8);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PowerBank Z', 'Portable power bank', 11.13,'Accessory',28);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('CarMount T', 'Car mount for phone', 19.76,'Accessory',80);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('WirelessCharger S', 'Wireless charging pad', 12.73,'Accessory',76);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BluetoothSpeaker R', 'Portable Bluetooth speaker', 44.51,'Accessory',31);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('SelfieStick V', 'Extendable selfie stick', 6.44,'Accessory',25);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PhoneStand A', 'Adjustable phone stand', 8.69,'Accessory',32);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('MemoryCard M', 'High-capacity memory card', 45.53,'Accessory',81);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Earbuds E', 'Wired in-ear earbuds', 6.36,'Accessory',100);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Stylus Pen', 'Precision stylus pen', 7.55,'Accessory',52);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('CleaningKit C', 'Phone cleaning kit', 9.67,'Accessory',15);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('LensKit L', 'Clip-on camera lens kit', 31.75,'Accessory',32);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('VRHeadset V', 'Virtual reality headset', 50.49,'Accessory',26);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('GameController G', 'Bluetooth game controller', 46.47,'Accessory',24);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('SmartWatch S', 'Smartwatch with fitness tracking', 115.02,'Accessory',96);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('FitnessBand F', 'Fitness tracking band', 69.02,'Accessory',53);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('USBHub U', 'Multi-port USB hub', 23.89,'Accessory',11);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('OTGCable O', 'OTG cable for phone', 7.98,'Accessory',2);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('HDMIAdapter H', 'HDMI adapter for phone', 17.58,'Accessory',57);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('CarCharger C', 'Car charger with dual USB ports', 9.38,'Accessory',97);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('WallCharger W', 'Wall charger with fast charging', 28.28,'Accessory',58);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('TravelAdapter T', 'Universal travel adapter', 11.23,'Accessory',45);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('WirelessEarbuds W', 'True wireless earbuds', 65.53,'Accessory',67);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BluetoothHeadset B', 'Bluetooth headset with mic', 41.98,'Accessory',2);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ScreenCleaner S', 'Screen cleaning wipes', 11.11,'Accessory',74);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PhoneRingHolder P', 'Phone ring holder and stand', 7.52,'Accessory',37);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('CableOrganizer C', 'Cable organizer clips', 5.41,'Accessory',78);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PhoneWallet P', 'Phone wallet case', 28.32,'Accessory',76);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BatteryCase B', 'Battery case for phone', 48.17,'Accessory',90);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('MagneticMount M', 'Magnetic car mount', 16.8,'Accessory',72);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PhoneLanyard P', 'Phone lanyard with strap', 12.41,'Accessory',89);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('WaterproofCase W', 'Waterproof phone case', 15.26,'Accessory',78);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Armband A', 'Phone armband for running', 15.07,'Accessory',79);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BikeMount B', 'Bike mount for phone', 10.3,'Accessory',14);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ScreenGuard Pro', 'Tempered glass screen protector', 8.65,'Accessory',29);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('CaseMate X', 'Durable phone case', 21.92,'Accessory',78);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PowerBank Z', 'Portable power bank', 52.45,'Accessory',81);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('CarMount T', 'Car mount for phone', 13.83,'Accessory',42);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('WirelessCharger S', 'Wireless charging pad', 30.8,'Accessory',17);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BluetoothSpeaker R', 'Portable Bluetooth speaker', 35.94,'Accessory',93);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('SelfieStick V', 'Extendable selfie stick', 6.92,'Accessory',68);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PhoneStand A', 'Adjustable phone stand', 14.35,'Accessory',56);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('MemoryCard M', 'High-capacity memory card', 46.83,'Accessory',76);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Earbuds E', 'Wired in-ear earbuds', 21.75,'Accessory',6);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Stylus Pen', 'Precision stylus pen', 11.31,'Accessory',53);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('CleaningKit C', 'Phone cleaning kit', 5.35,'Accessory',55);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('LensKit L', 'Clip-on camera lens kit', 31.59,'Accessory',57);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('VRHeadset V', 'Virtual reality headset', 58.66,'Accessory',1);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('GameController G', 'Bluetooth game controller', 43.22,'Accessory',58);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('SmartWatch S', 'Smartwatch with fitness tracking', 185.73,'Accessory',87);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('FitnessBand F', 'Fitness tracking band', 63.2,'Accessory',92);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('USBHub U', 'Multi-port USB hub', 20.51,'Accessory',10);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('OTGCable O', 'OTG cable for phone', 7.98,'Accessory',80);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('HDMIAdapter H', 'HDMI adapter for phone', 21.81,'Accessory',90);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('CarCharger C', 'Car charger with dual USB ports', 16.37,'Accessory',99);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('WallCharger W', 'Wall charger with fast charging', 22.55,'Accessory',41);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('TravelAdapter T', 'Universal travel adapter', 32.99,'Accessory',76);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('WirelessEarbuds W', 'True wireless earbuds', 41.86,'Accessory',93);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BluetoothHeadset B', 'Bluetooth headset with mic', 43.64,'Accessory',33);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ScreenCleaner S', 'Screen cleaning wipes', 6.61,'Accessory',31);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PhoneRingHolder P', 'Phone ring holder and stand', 7.8,'Accessory',95);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('CableOrganizer C', 'Cable organizer clips', 9.69,'Accessory',66);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PhoneWallet P', 'Phone wallet case', 29.97,'Accessory',53);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BatteryCase B', 'Battery case for phone', 48.09,'Accessory',14);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('MagneticMount M', 'Magnetic car mount', 6.16,'Accessory',87);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PhoneLanyard P', 'Phone lanyard with strap', 7.8,'Accessory',27);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('WaterproofCase W', 'Waterproof phone case', 14.33,'Accessory',10);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Armband A', 'Phone armband for running', 7.62,'Accessory',32);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BikeMount B', 'Bike mount for phone', 21.74,'Accessory',99);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('SoundMax Pro', 'High-quality over-ear headphones', 93.41,'Headphone',22);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BassBoost X', 'In-ear headphones with deep bass', 95.04,'Headphone',93);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ClearTone S', 'Wireless headphones with clear sound', 226.67,'Headphone',71);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('NoiseBlocker Z', 'Noise-cancelling headphones', 315.74,'Headphone',19);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('AudioWave T', 'True wireless earbuds', 232.59,'Headphone',72);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Harmony H', 'Headphones with balanced sound', 163.32,'Headphone',68);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('EchoFree R', 'Headphones with echo reduction', 77.86,'Headphone',58);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BeatMaster V', 'Headphones with enhanced bass', 179.19,'Headphone',63);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('TunePro A', 'Headphones with adjustable sound', 109.24,'Headphone',60);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Melody M', 'Headphones with rich sound', 163.95,'Headphone',37);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Rhythm R', 'Headphones with rhythmic sound', 145.29,'Headphone',34);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Vibe X', 'Headphones with vibrant sound', 125.54,'Headphone',44);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Pulse P', 'Headphones with pulsating sound', 137.28,'Headphone',12);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Harmony H2', 'Headphones with harmonic sound', 121.61,'Headphone',20);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Clarity C', 'Headphones with crystal clear sound', 151.32,'Headphone',64);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('AlphaPhone X1', 'Alpha Phone: 5.8-inch display, available in black. Comes with 64GB storage and a 16MP dual-camera system.', 1424.25,'Phone',81);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BetaPhone Z2', 'Beta Phone: 6.5-inch display, available in silver, gold, and green. Comes with 256GB storage and a 48MP triple-camera system.', 824.57,'Phone',69);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('GammaPhone Pro', 'Gamma Phone: 5.8-inch display, available in red, black, and white. Comes with 64GB storage and a 16MP dual-camera system.', 1695.76,'Phone',19);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('DeltaPhone Lite', 'Delta Phone: 6.7-inch display, available in blue, black, and silver. Comes with 512GB storage and a 108MP quad-camera system.', 674.26,'Phone',82);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('EpsilonPhone Max', 'Epsilon Phone: 6.3-inch display, available in purple, black, and white. Comes with 128GB storage and a 32MP triple-camera system.', 714.61,'Phone',89);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ZetaPhone Mini', 'Zeta Phone: 6.0-inch display, available in yellow, black, and white. Comes with 128GB storage and a 20MP dual-camera system.', 1005.46,'Phone',55);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('EtaPhone Ultra', 'Eta Phone: 6.4-inch display, available in green, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 1508.9,'Phone',31);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ThetaPhone S', 'Eta Phone: 6.4-inch display, available in green, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 973.14,'Phone',26);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('IotaPhone R', 'Iota Phone: 6.2-inch display, available in pink, black, and white. Comes with 128GB storage and a 24MP dual-camera system.', 613.44,'Phone',36);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('KappaPhone T', 'Kappa Phone: 6.6-inch display, available in orange, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 1418.49,'Phone',20);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('LambdaPhone V', 'Lambda Phone: 6.1-inch display, available in cyan, black, and white. Comes with 128GB storage and a 20MP dual-camera system.', 940.55,'Phone',80);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('MuPhone A', 'Mu Phone: 6.3-inch display, available in magenta, black, and white. Comes with 256GB storage and a 32MP triple-camera system.', 806.82,'Phone',56);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('NuPhone B', 'Nu Phone: 6.5-inch display, available in teal, black, and white. Comes with 512GB storage and a 64MP quad-camera system.', 1111.08,'Phone',66);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('XiPhone C', 'Xi Phone: 6.7-inch display, available in violet, black, and white. Comes with 128GB storage and a 12MP dual-camera system.', 783.87,'Phone',31);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('OmicronPhone D', 'Omicron Phone: 6.8-inch display, available in indigo, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 753.58,'Phone',5);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PiPhone E', 'Pi Phone: 6.0-inch display, available in lime, black, and white. Comes with 64GB storage and a 16MP dual-camera system.', 720.44,'Phone',57);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('RhoPhone F', 'Rho Phone: 6.2-inch display, available in brown, black, and white. Comes with 128GB storage and a 24MP dual-camera system.', 1623.34,'Phone',92);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('SigmaPhone G', 'Sigma Phone: 6.4-inch display, available in beige, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 1941.09,'Phone',24);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('TauPhone H', 'Tau Phone: 6.6-inch display, available in maroon, black, and white. Comes with 512GB storage and a 108MP quad-camera system.', 1581.11,'Phone',54);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('UpsilonPhone I', 'Upsilon Phone: 6.1-inch display, available in navy, black, and white. Comes with 128GB storage and a 20MP dual-camera system.', 2112.08,'Phone',58);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PhiPhone J', 'Phi Phone: 6.3-inch display, available in olive, black, and white. Comes with 256GB storage and a 32MP triple-camera system.', 1857.03,'Phone',52);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ChiPhone K', 'Chi Phone: 6.5-inch display, available in coral, black, and white. Comes with 512GB storage and a 64MP quad-camera system.', 2000.04,'Phone',8);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PsiPhone L', 'Psi Phone: 6.7-inch display, available in lavender, black, and white. Comes with 128GB storage and a 12MP dual-camera system.', 2391.99,'Phone',82);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('OmegaPhone M', 'Omega Phone: 6.8-inch display, available in mint, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 1512.01,'Phone',12);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('AlphaPhone N', 'Alpha Phone: 6.1-inch display, available in black. Comes with 128GB storage and a 12MP dual-camera system.', 2307.46,'Phone',81);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BetaPhone O', 'Beta Phone: 6.5-inch display, available in silver, gold, and green. Comes with 256GB storage and a 48MP triple-camera system.', 1754.01,'Phone',50);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('GammaPhone P', 'Gamma Phone: 5.8-inch display, available in red, black, and white. Comes with 64GB storage and a 16MP dual-camera system.', 1273.83,'Phone',40);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('DeltaPhone Q', 'Delta Phone: 6.7-inch display, available in blue, black, and silver. Comes with 512GB storage and a 108MP quad-camera system.', 2362.21,'Phone',3);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('EpsilonPhone R', 'Epsilon Phone: 6.3-inch display, available in purple, black, and white. Comes with 128GB storage and a 32MP triple-camera system.', 2089,'Phone',6);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ZetaPhone S', 'Zeta Phone: 6.0-inch display, available in yellow, black, and white. Comes with 128GB storage and a 20MP dual-camera system.', 1795.49,'Phone',47);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('EtaPhone T', 'Eta Phone: 6.4-inch display, available in green, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 2450.15,'Phone',24);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ThetaPhone U', 'Eta Phone: 6.4-inch display, available in green, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 3591.37,'Phone',93);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('IotaPhone V', 'Iota Phone: 6.2-inch display, available in pink, black, and white. Comes with 128GB storage and a 24MP dual-camera system.', 4022.89,'Phone',44);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('KappaPhone W', 'Kappa Phone: 6.6-inch display, available in orange, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 1514.33,'Phone',63);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('LambdaPhone X', 'Lambda Phone: 6.1-inch display, available in cyan, black, and white. Comes with 128GB storage and a 20MP dual-camera system.', 3643.13,'Phone',61);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('MuPhone Y', 'Mu Phone: 6.3-inch display, available in magenta, black, and white. Comes with 256GB storage and a 32MP triple-camera system.', 2815.59,'Phone',75);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('NuPhone Z', 'Nu Phone: 6.5-inch display, available in teal, black, and white. Comes with 512GB storage and a 64MP quad-camera system.', 3651.31,'Phone',18);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('XiPhone Alpha', 'Alpha Phone: 6.5-inch display, available in silver. Comes with 256GB storage and a 48MP triple-camera system.', 3966.01,'Phone',92);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('OmicronPhone Beta', 'Beta Phone: 6.5-inch display, available in silver, gold, and green. Comes with 256GB storage and a 48MP triple-camera system.', 5124.98,'Phone',87);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PiPhone Gamma', 'Gamma Phone: 5.8-inch display, available in red, black, and white. Comes with 64GB storage and a 16MP dual-camera system.', 4814.33,'Phone',98);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('RhoPhone Delta', 'Delta Phone: 6.7-inch display, available in blue, black, and silver. Comes with 512GB storage and a 108MP quad-camera system.', 4076.5,'Phone',36);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('SigmaPhone Epsilon', 'Epsilon Phone: 6.3-inch display, available in purple, black, and white. Comes with 128GB storage and a 32MP triple-camera system.', 2438.06,'Phone',87);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('TauPhone Zeta', 'Zeta Phone: 6.0-inch display, available in yellow, black, and white. Comes with 128GB storage and a 20MP dual-camera system.', 2382.91,'Phone',72);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('UpsilonPhone Eta', 'Eta Phone: 6.4-inch display, available in green, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 2826.99,'Phone',60);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PhiPhone Theta', 'Eta Phone: 6.4-inch display, available in green, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 2323.92,'Phone',41);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('ChiPhone Iota', 'Iota Phone: 6.2-inch display, available in pink, black, and white. Comes with 128GB storage and a 24MP dual-camera system.', 5580.87,'Phone',98);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('PsiPhone Kappa', 'Kappa Phone: 6.6-inch display, available in orange, black, and white. Comes with 256GB storage and a 48MP triple-camera system.', 4411.76,'Phone',18);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('OmegaPhone Lambda', 'Lambda Phone: 6.1-inch display, available in cyan, black, and white. Comes with 128GB storage and a 20MP dual-camera system.', 5702.03,'Phone',29);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('AlphaPhone Mu', 'Alpha Phone: 6.5-inch display, available in gold. Comes with 256GB storage and a 48MP triple-camera system.', 4809.1,'Phone',40);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('BetaPhone Nu', 'Beta Phone: 6.5-inch display, available in silver, gold, and green. Comes with 256GB storage and a 48MP triple-camera system.', 4120.66,'Phone',19);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for AlphaPhone X1', 'Fast charging adapter', 10.65,'Charger',42);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for AlphaPhone X1', 'Universal charging adapter', 32.29,'Charger',8);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for GammaPhone Pro', 'Fast charging adapter', 18.18,'Charger',40);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for GammaPhone Pro', 'Universal charging adapter', 29.93,'Charger',24);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for EpsilonPhone Max', 'Fast charging adapter', 21.43,'Charger',49);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for EpsilonPhone Max', 'Universal charging adapter', 12.3,'Charger',58);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for EtaPhone Ultra', 'Fast charging adapter', 16.71,'Charger',20);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for EtaPhone Ultra', 'Universal charging adapter', 17.4,'Charger',3);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for IotaPhone R', 'Fast charging adapter', 18.4,'Charger',1);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for IotaPhone R', 'Universal charging adapter', 25.53,'Charger',14);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for LambdaPhone V', 'Fast charging adapter', 31.74,'Charger',34);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for LambdaPhone V', 'Universal charging adapter', 15,'Charger',88);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for NuPhone B', 'Fast charging adapter', 12.11,'Charger',65);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for NuPhone B', 'Universal charging adapter', 10.54,'Charger',39);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for OmicronPhone D', 'Fast charging adapter', 33.15,'Charger',45);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for OmicronPhone D', 'Universal charging adapter', 11.57,'Charger',42);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for RhoPhone F', 'Fast charging adapter', 35.68,'Charger',75);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for RhoPhone F', 'Universal charging adapter', 14.39,'Charger',5);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for TauPhone H', 'Fast charging adapter', 29.2,'Charger',90);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for TauPhone H', 'Universal charging adapter', 16.07,'Charger',70);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for PhiPhone J', 'Fast charging adapter', 19.04,'Charger',46);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for PhiPhone J', 'Universal charging adapter', 21.38,'Charger',33);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for PsiPhone L', 'Fast charging adapter', 29.2,'Charger',70);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for PsiPhone L', 'Universal charging adapter', 17.54,'Charger',26);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for AlphaPhone N', 'Fast charging adapter', 27.59,'Charger',82);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for AlphaPhone N', 'Universal charging adapter', 10.05,'Charger',30);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for GammaPhone P', 'Fast charging adapter', 20.5,'Charger',83);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for GammaPhone P', 'Universal charging adapter', 31.03,'Charger',40);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for EpsilonPhone R', 'Fast charging adapter', 37.08,'Charger',38);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for EpsilonPhone R', 'Universal charging adapter', 33.6,'Charger',31);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for EtaPhone T', 'Fast charging adapter', 30.42,'Charger',58);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for EtaPhone T', 'Universal charging adapter', 26.92,'Charger',96);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for IotaPhone V', 'Fast charging adapter', 29.81,'Charger',98);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for IotaPhone V', 'Universal charging adapter', 23.46,'Charger',24);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for LambdaPhone X', 'Fast charging adapter', 26.76,'Charger',42);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for LambdaPhone X', 'Universal charging adapter', 24.68,'Charger',88);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for NuPhone Z', 'Fast charging adapter', 33.28,'Charger',100);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for NuPhone Z', 'Universal charging adapter', 11.17,'Charger',46);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for OmicronPhone Beta', 'Fast charging adapter', 13.98,'Charger',79);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for OmicronPhone Beta', 'Universal charging adapter', 32.21,'Charger',22);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for RhoPhone Delta', 'Fast charging adapter', 32.62,'Charger',100);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for RhoPhone Delta', 'Universal charging adapter', 28.92,'Charger',3);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for TauPhone Zeta', 'Fast charging adapter', 38.61,'Charger',77);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for TauPhone Zeta', 'Universal charging adapter', 12.27,'Charger',8);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for PhiPhone Theta', 'Fast charging adapter', 10.68,'Charger',43);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for PhiPhone Theta', 'Universal charging adapter', 18.08,'Charger',96);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for PsiPhone Kappa', 'Fast charging adapter', 29.16,'Charger',77);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for PsiPhone Kappa', 'Universal charging adapter', 20.56,'Charger',24);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Charger for AlphaPhone Mu', 'Fast charging adapter', 13.38,'Charger',37);
INSERT INTO [dbo].dim_products (ProductName, Description, Price, Category, StockQuantity) VALUES ('Adapter for AlphaPhone Mu', 'Universal charging adapter', 24.29,'Charger',29);