apiVersion: v1
kind: ServiceAccount
metadata:
  name: pharma-backend
  namespace: pharma
  annotations:
    azure.workload.identity/client-id: __UAMI_CLIENT_ID__
  labels:
    azure.workload.identity/use: "true"
