apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hcp-keyvault-secrets-provider
  namespace: hcp-portal
spec:
  provider: azure
  secretObjects:
    - secretName: hcp-keyvault-secrets
      type: Opaque
      data:
        - objectName: sql-connection-string
          key: sql-connection-string
        - objectName: postgres-connection-string
          key: postgres-connection-string
        - objectName: redis-connection-string
          key: redis-connection-string
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "KEYVAULT_CLIENT_ID_PLACEHOLDER"
    keyvaultName: "KEYVAULT_NAME_PLACEHOLDER"
    tenantId: "KEYVAULT_TENANT_ID_PLACEHOLDER"
    objects: |
      array:
        - |
          objectName: sql-connection-string
          objectType: secret
        - |
          objectName: postgres-connection-string
          objectType: secret
        - |
          objectName: redis-connection-string
          objectType: secret
