apiVersion: v1
kind: Service
metadata:
  name: hcp-portal-api
  namespace: hcp-portal
spec:
  selector:
    app: hcp-portal-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
