apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hcp-enrollment-worker-hpa
  namespace: hcp-portal-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hcp-enrollment-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
