name: Secret Scan
on:
  push:
  pull_request:
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Run TruffleHog Secret Scanner
        uses: "trufflesecurity/trufflehog@main"
        with:
          path: "."
          fail: true
