name: Weekly Traffic Report

on:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight

jobs:
  traffic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.repository.default_branch }}
    
    - name: Calculate traffic and generate report
      uses: sangonzal/repository-traffic-action@v0.1.2
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
     
    - name: Commit traffic report
      uses: EndBug/add-and-commit@v4
      with:
        author_name: GitHub Actions
        message: "Weekly traffic report"
        add: "./traffic/"
        ref: ${{ github.event.repository.default_branch }}
